/**
 * PINJEMIN — MOCK DATA
 * Used when backend is not available.
 */

export const MOCK_USER = {
  id: 'user-001',
  username: 'budi_santoso',
  fullName: 'Budi Santoso',
  phone: '+62811234567',
  avatarUrl: null,
  bio: 'Senang berbagi dan membantu komunitas sekitar. Mari jaga lingkungan bersama! 🌱',
  trustScore: 87,
  trustLevel: 'TRUSTED',
  totalLends: 24,
  totalBorrows: 18,
  successfulReturns: 17,
  neighborhood: 'Menteng',
  address: 'Menteng, Jakarta Pusat',
  createdAt: '2024-03-15T08:00:00Z',
};

export const MOCK_ITEMS = [
  {
    id: 'item-001',
    title: 'Mesin Bor Bosch GSB 550',
    description: 'Mesin bor listrik Bosch serbaguna, cocok untuk kayu dan tembok ringan. Dilengkapi mata bor berbagai ukuran.',
    category: 'TOOLS',
    condition: 'EXCELLENT',
    images: [],
    depositAmount: 50000,
    isAvailable: true,
    viewCount: 124,
    neighborhood: 'Menteng',
    distance: 1.2,
    tags: ['bor', 'listrik', 'bosch'],
    usageGuidelines: 'Harap kembalikan dalam kondisi bersih. Jangan gunakan untuk material yang terlalu keras.',
    ownerId: 'user-002',
    owner: { id: 'user-002', username: 'andi_p', fullName: 'Andi Pratama', trustScore: 92, trustLevel: 'VERIFIED', avatarUrl: null },
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'item-002',
    title: 'Tenda Camping Coleman 4 Orang',
    description: 'Tenda kapasitas 4 orang, waterproof, mudah dipasang. Cocok untuk camping weekend.',
    category: 'OUTDOOR',
    condition: 'GOOD',
    images: [],
    depositAmount: 100000,
    isAvailable: true,
    viewCount: 89,
    neighborhood: 'Gondangdia',
    distance: 2.5,
    tags: ['camping', 'tenda', 'outdoor'],
    usageGuidelines: 'Keringkan sebelum dikembalikan. Cek tiang dan pasak lengkap.',
    ownerId: 'user-003',
    owner: { id: 'user-003', username: 'sari_d', fullName: 'Sari Dewi', trustScore: 78, trustLevel: 'TRUSTED', avatarUrl: null },
    createdAt: '2025-02-05T14:00:00Z',
  },
  {
    id: 'item-003',
    title: 'Proyektor Epson EB-X41',
    description: 'Proyektor portabel 3600 lumen. Cocok untuk presentasi dan nonton bareng.',
    category: 'ELECTRONICS',
    condition: 'EXCELLENT',
    images: [],
    depositAmount: 200000,
    isAvailable: false,
    viewCount: 210,
    neighborhood: 'Cikini',
    distance: 0.8,
    tags: ['proyektor', 'presentasi', 'epson'],
    usageGuidelines: 'Handle with care. Jangan sentuh lensa. Kembalikan dengan kabel lengkap.',
    ownerId: 'user-001',
    owner: MOCK_USER,
    createdAt: '2025-01-20T09:00:00Z',
  },
  {
    id: 'item-004',
    title: 'Mixer Stand KitchenAid Artisan',
    description: 'Mixer premium 4.8L untuk baking. Lengkap dengan berbagai attachment.',
    category: 'KITCHEN',
    condition: 'GOOD',
    images: [],
    depositAmount: 150000,
    isAvailable: true,
    viewCount: 67,
    neighborhood: 'Pegangsaan',
    distance: 1.8,
    tags: ['mixer', 'baking', 'kitchenaid'],
    usageGuidelines: 'Cuci semua attachment sebelum dikembalikan.',
    ownerId: 'user-004',
    owner: { id: 'user-004', username: 'maya_k', fullName: 'Maya Kusuma', trustScore: 65, trustLevel: 'MEMBER', avatarUrl: null },
    createdAt: '2025-03-01T11:00:00Z',
  },
  {
    id: 'item-005',
    title: 'Sepeda Gunung MTB Polygon',
    description: 'MTB Polygon Xtrada 5 ukuran M. Cocok untuk track menengah.',
    category: 'SPORTS',
    condition: 'GOOD',
    images: [],
    depositAmount: 200000,
    isAvailable: true,
    viewCount: 183,
    neighborhood: 'Menteng',
    distance: 0.5,
    tags: ['sepeda', 'mtb', 'polygon'],
    usageGuidelines: 'Kembalikan dalam kondisi bersih. Periksa tekanan ban sebelum dikembalikan.',
    ownerId: 'user-005',
    owner: { id: 'user-005', username: 'fajar_n', fullName: 'Fajar Nugroho', trustScore: 55, trustLevel: 'MEMBER', avatarUrl: null },
    createdAt: '2025-02-14T16:00:00Z',
  },
  {
    id: 'item-006',
    title: 'Buku "Atomic Habits" James Clear',
    description: 'Buku best-seller tentang membangun kebiasaan baik. Kondisi sangat baik.',
    category: 'BOOKS_MEDIA',
    condition: 'EXCELLENT',
    images: [],
    depositAmount: 0,
    isAvailable: true,
    viewCount: 45,
    neighborhood: 'Gondangdia',
    distance: 2.1,
    tags: ['buku', 'self-help', 'atomic-habits'],
    usageGuidelines: 'Jaga kondisi buku. Jangan lipat halaman.',
    ownerId: 'user-003',
    owner: { id: 'user-003', username: 'sari_d', fullName: 'Sari Dewi', trustScore: 78, trustLevel: 'TRUSTED', avatarUrl: null },
    createdAt: '2025-04-10T10:00:00Z',
  },
];

export const MOCK_REQUESTS = [
  {
    id: 'req-001',
    itemId: 'item-001',
    item: MOCK_ITEMS[0],
    borrowerId: 'user-001',
    borrower: MOCK_USER,
    lenderId: 'user-002',
    lender: { id: 'user-002', username: 'andi_p', fullName: 'Andi Pratama', trustScore: 92, trustLevel: 'VERIFIED', avatarUrl: null },
    status: 'APPROVED',
    purpose: 'Mau pasang rak di ruang tamu, butuh bor sekitar 2 jam',
    startDate: '2026-05-15T00:00:00Z',
    endDate: '2026-05-15T23:59:00Z',
    message: 'Halo, boleh saya pinjam bornya?',
    createdAt: '2026-05-11T08:00:00Z',
  },
  {
    id: 'req-002',
    itemId: 'item-002',
    item: MOCK_ITEMS[1],
    borrowerId: 'user-001',
    borrower: MOCK_USER,
    lenderId: 'user-003',
    lender: { id: 'user-003', username: 'sari_d', fullName: 'Sari Dewi', trustScore: 78, trustLevel: 'TRUSTED', avatarUrl: null },
    status: 'PENDING',
    purpose: 'Camping di Sentul minggu ini bareng keluarga',
    startDate: '2026-05-17T00:00:00Z',
    endDate: '2026-05-19T23:59:00Z',
    message: '',
    createdAt: '2026-05-11T10:30:00Z',
  },
];

export const MOCK_APPROVALS = [
  {
    id: 'req-003',
    itemId: 'item-003',
    item: MOCK_ITEMS[2],
    borrowerId: 'user-005',
    borrower: { id: 'user-005', username: 'fajar_n', fullName: 'Fajar Nugroho', trustScore: 55, trustLevel: 'MEMBER', avatarUrl: null },
    lenderId: 'user-001',
    lender: MOCK_USER,
    status: 'PENDING',
    purpose: 'Presentasi bisnis di kantor, butuh proyektor 1 hari',
    startDate: '2026-05-13T00:00:00Z',
    endDate: '2026-05-13T23:59:00Z',
    message: 'Halo kak, boleh pinjam proyektornya untuk presentasi besok?',
    createdAt: '2026-05-11T07:00:00Z',
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif-001',
    type: 'BORROW_REQUEST_RECEIVED',
    title: 'Ada yang mau meminjam! 📦',
    body: 'Fajar Nugroho ingin meminjam Proyektor Epson EB-X41 dari 13 Mei – 13 Mei.',
    isRead: false,
    createdAt: '2026-05-11T07:00:00Z',
    data: { requestId: 'req-003' },
  },
  {
    id: 'notif-002',
    type: 'BORROW_REQUEST_APPROVED',
    title: 'Permintaan Disetujui! ✅',
    body: 'Andi Pratama menyetujui peminjaman Mesin Bor Bosch GSB 550.',
    isRead: false,
    createdAt: '2026-05-11T06:30:00Z',
    data: { requestId: 'req-001' },
  },
  {
    id: 'notif-003',
    type: 'TRUST_SCORE_CHANGED',
    title: 'Trust Score Kamu Naik! 🚀',
    body: 'Trust score kamu sekarang 87. Kamu semakin dipercaya komunitas!',
    isRead: true,
    createdAt: '2026-05-10T15:00:00Z',
    data: {},
  },
];
