name: DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: pinjemin-backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Fix Binary Permissions
        run: chmod +x ./node_modules/.bin/*

      - name: Generate Prisma Client
        run: ./node_modules/.bin/prisma generate

      - name: Build Docker Image
        run: docker build -t pinjemin-backend .
